// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/blog" | "/blog/:slug";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/blog-list.tsx": {
    id: "routes/blog-list";
    page: "/blog";
  };
  "routes/blog-post.tsx": {
    id: "routes/blog-post";
    page: "/blog/:slug";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/index": typeof import("./src/routes/index.tsx");
  "routes/blog-list": typeof import("./src/routes/blog-list.tsx");
  "routes/blog-post": typeof import("./src/routes/blog-post.tsx");
};